version: "3"

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306 
    volumes:
      - ./mysql:/mysql/conf.d
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/log:/mysql/log/mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake


  web:
    build: .
    volumes: 
      - ./:/go/src/github.com/ryo.hidaka/compose
    ports:
      - 8080:8080
    depends_on:
      - db

  proxy:
    build: nginx/.
    ports:
      - 8000:80
    depends_on:
      - web
